### ISSUE TITLE
Host tag shouldn't be set for percentiles

### ISSUE THREAD

**Issue by jtblin** [atlassian/gostatsd#116] opened 2017-08-10 04:50 UTC
Percentiles should be calculated across hosts. Because we add the `host` tag automatically (as per Datadog agent), percentiles are not calculated properly. Fixing this issue might make the code failry complex though, not sure as I haven't looked into it for a while.

**Comment by tiedotguy** [comment] 2017-08-10 05:18
The issues caused by this internally are addressed in #77.  If it's required by the community I can look in to it though.

**Comment by aelse** [comment] 2018-01-16 09:34
@tiedotguy Can this issue now be closed since #77 was resolved?

**Comment by tiedotguy** [comment] 2018-01-16 10:13
It's still a valid issue for the larger community, it's just unlikely to get our time scheduled to work on it.

**Comment by aelse** [comment] 2018-01-16 23:03
I'm going to close this off. #77 adds a flag to disable automatically injecting a host tag. Apps can decide for which metrics to include a host tag, so they can include them for gauges/counters and not timers.

**Closed by aelse** 2018-01-16 23:03 UTC
